In [1]:
import nltk

In [2]:
#Stopwords
from nltk.corpus import stopwords
stopwords.words('english')

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [3]:
#CMU Wordlist
entries=nltk.corpus.cmudict.entries()
len(entries)

133737

In [4]:
entries[:50]

[('a', ['AH0']),
 ('a.', ['EY1']),
 ('a', ['EY1']),
 ('a42128',
  ['EY1',
   'F',
   'AO1',
   'R',
   'T',
   'UW1',
   'W',
   'AH1',
   'N',
   'T',
   'UW1',
   'EY1',
   'T']),
 ('aaa', ['T', 'R', 'IH2', 'P', 'AH0', 'L', 'EY1']),
 ('aaberg', ['AA1', 'B', 'ER0', 'G']),
 ('aachen', ['AA1', 'K', 'AH0', 'N']),
 ('aachener', ['AA1', 'K', 'AH0', 'N', 'ER0']),
 ('aaker', ['AA1', 'K', 'ER0']),
 ('aalseth', ['AA1', 'L', 'S', 'EH0', 'TH']),
 ('aamodt', ['AA1', 'M', 'AH0', 'T']),
 ('aancor', ['AA1', 'N', 'K', 'AO2', 'R']),
 ('aardema', ['AA0', 'R', 'D', 'EH1', 'M', 'AH0']),
 ('aardvark', ['AA1', 'R', 'D', 'V', 'AA2', 'R', 'K']),
 ('aaron', ['EH1', 'R', 'AH0', 'N']),
 ("aaron's", ['EH1', 'R', 'AH0', 'N', 'Z']),
 ('aarons', ['EH1', 'R', 'AH0', 'N', 'Z']),
 ('aaronson', ['EH1', 'R', 'AH0', 'N', 'S', 'AH0', 'N']),
 ('aaronson', ['AA1', 'R', 'AH0', 'N', 'S', 'AH0', 'N']),
 ("aaronson's", ['EH1', 'R', 'AH0', 'N', 'S', 'AH0', 'N', 'Z']),
 ("aaronson's", ['AA1', 'R', 'AH0', 'N', 'S', 'AH0', 'N', 'Z'

In [5]:
#Synset is a special kind of a simple interface that is present in NLTK to look up words in WordNet.
#WordNet is the lexical database i.e. dictionary for the English language, specifically designed for
#natural language processing.
from nltk.corpus import wordnet as wn
wn.synsets('good')

[Synset('good.n.01'),
 Synset('good.n.02'),
 Synset('good.n.03'),
 Synset('commodity.n.01'),
 Synset('good.a.01'),
 Synset('full.s.06'),
 Synset('good.a.03'),
 Synset('estimable.s.02'),
 Synset('beneficial.s.01'),
 Synset('good.s.06'),
 Synset('good.s.07'),
 Synset('adept.s.01'),
 Synset('good.s.09'),
 Synset('dear.s.02'),
 Synset('dependable.s.04'),
 Synset('good.s.12'),
 Synset('good.s.13'),
 Synset('effective.s.04'),
 Synset('good.s.15'),
 Synset('good.s.16'),
 Synset('good.s.17'),
 Synset('good.s.18'),
 Synset('good.s.19'),
 Synset('good.s.20'),
 Synset('good.s.21'),
 Synset('well.r.01'),
 Synset('thoroughly.r.02')]

In [6]:
wn.synset('good.s.21').lemma_names()

['good']

In [7]:
wn.synset('effective.s.04').lemma_names()

['effective', 'good', 'in_effect', 'in_force']

In [8]:
def gender_features(word):
    return {'last_letter':word[-1]}
gender_features('Obama')

{'last_letter': 'a'}

In [9]:
#so what we are trying to do here is that for every last letter of name we are adding the male and female tag to it 
#and then we will try to train our model based on that
from nltk.corpus import names
labeled_names = ([(name, 'male') for name in names.words('male.txt')]+
                [(name, 'female') for name in names.words('female.txt')])

In [10]:
import random
random.shuffle(labeled_names)

In [11]:
featuresets=[(gender_features(n),gender) for (n,gender) in labeled_names]

In [12]:
train_set,test_set=featuresets[500:], featuresets[:500]

In [13]:
#Using Naivebayes classifier to classify
import nltk
classifier=nltk.NaiveBayesClassifier.train(train_set)

In [14]:
classifier.classify(gender_features('Obama'))

'female'

In [15]:
classifier.classify(gender_features('Saurabh'))

'female'

In [16]:
print(nltk.classify.accuracy(classifier,test_set))

0.774


# Vectorizer

In [17]:
#vectorizer is converting your text to numerical format

In [18]:
from sklearn.feature_extraction.text import CountVectorizer

In [19]:
corpus = ["Tessaract is good optical character recognition engine  ", "optical character recognition is significant "]

In [20]:
vect= CountVectorizer(binary=True)
corpus=['PCA is good for feature extraction','feature extraction is necessary forclassification task']
vect.fit(corpus)

CountVectorizer(analyzer='word', binary=True, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

In [21]:
vocab=vect.vocabulary_

In [22]:
for key in sorted(vocab.keys()):
    print("{}:{}".format(key, vocab[key]))

extraction:0
feature:1
for:2
forclassification:3
good:4
is:5
necessary:6
pca:7
task:8


In [23]:
print(vect.transform(["machine learning task"]).toarray())

[[0 0 0 0 0 0 0 0 1]]


In [24]:
print(vect.transform(corpus).toarray())

[[1 1 1 0 1 1 0 1 0]
 [1 1 0 1 0 1 1 0 1]]


In [25]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [26]:
vect=CountVectorizer(binary=True)
corpus=["Tessaract is good optical character recognition engine  ", "optical character recognition is significant"]
vect.fit(corpus)

CountVectorizer(analyzer='word', binary=True, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

In [27]:
#Cosine similarity measures the similarity between two vectors of an inner product space.
# It is measured by the cosine of the angle between two vectors and determines whether two vectors 
# are pointing in roughly the same direction. 
# It is often used to measure document similarity in text analysis.

In [28]:
from sklearn.metrics.pairwise import cosine_similarity

In [29]:
#two 1D vector is created and then calculating the cosine similarity between them
similarity = cosine_similarity(vect.transform(["Google Cloud Vision is a character recognition engine"]).toarray(), vect.transform(["OCR is an optical character recognition engine"]).toarray())

In [30]:
print(similarity) 

[[0.89442719]]


In [31]:
similarity=cosine_similarity(vect.transform(["block looks bad "]).toarray(),vect.transform(["saurabh is a good boy"]).toarray())
print(similarity)

[[0.]]
